FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY ["codigo_projeto/backend/src/product/package.json", "codigo_projeto/backend/src/product/.env", "./"]

COPY codigo_projeto/backend/src/product/src ./src

# Install application dependencies
RUN npm install

# Expose the port your application will run on
EXPOSE 8001

# Define the command to start your application
CMD ["npm", "run", "dev"]
