apiVersion: v1
kind: Service
metadata:
  name: devops-api
spec:
  selector:
    app: api-container
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiTargetPort }}
    # - name: plans
    #   protocol: TCP
    #   port: {{ .Values.service.plansPort }}
    #   targetPort: {{ .Values.service.plansTargetPort }}
    # - name: products
    #   protocol: TCP
    #   port: {{ .Values.service.productsPort }}
    #   targetPort: {{ .Values.service.productsTargetPort }}
  type: {{ .Values.service.type }}
