apiVersion: v1
kind: Service
metadata:
  name: devops-plans
spec:
  selector:
    app: plans-container
  ports:
    - name: plans
      protocol: TCP
      port: {{ .Values.service.plansPort }}
      targetPort: {{ .Values.service.plansTargetPort }}
  type: {{ .Values.service.type }}
