apiVersion: v1
kind: Service
metadata:
  name: devops-product
spec:
  selector:
    app: product-container
  ports:
    - name: products
      protocol: TCP
      port: {{ .Values.service.productsPort }}
      targetPort: {{ .Values.service.productsTargetPort }}
  type: {{ .Values.service.type }}
